import{a as v,S as T,i as c}from"./assets/vendor-da186403.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&n(u)}).observe(document,{childList:!0,subtree:!0});function s(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(r){if(r.ep)return;r.ep=!0;const o=s(r);fetch(r.href,o)}})();const M="42710952-cb07850fe6c5f6774b64d780f",S="https://pixabay.com/api/";async function g(t,e,s){try{return(await v.get(S,{params:{key:M,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:s}})).data}catch(n){throw console.error("Error fetching images:",n),n}}const a=document.querySelector(".gallery"),L=new T(".gallery a",{captionsData:"alt",captionDelay:250});L.refresh();function E(t){t.forEach(e=>{const s=`
      <li class="card">
        <a href="${e.largeImageURL}" class="link">
          <img src="${e.webformatURL}" alt="${e.tags}">
          <ul class="list-container">
          <li class="item-description"><h3>Likes</h3> <p>${e.likes}</p></li>
          <li class="item-description"><h3>Views</h3> <p>${e.views}</p></li>
          <li class="item-description"><h3>Comments</h3> <p>${e.comments}</p></li>
          <li class="item-description"><h3>Downloads</h3> <p>${e.downloads}</p></li>
        </ul>
        </a>
        
      </li>
    `;a.insertAdjacentHTML("beforeend",s)}),L.refresh()}function C(){const t=document.createElement("p");t.classList.add("end-message"),t.textContent="We're sorry, but you've reached the end of search results.",a.insertAdjacentElement("afterend",t)}const f=document.querySelector(".scroll-to-top"),q=document.querySelector(".form"),y=document.querySelector(".search-input"),w=document.querySelector(".loader"),d=document.querySelector(".load-more-btn");p();let l="",i=1;const m=15;q.addEventListener("submit",P);async function P(t){if(t.preventDefault(),l=y.value.trim(),i=1,a.innerHTML="",l===""){c.error({title:"Error",message:"Please enter a search term.",position:"topCenter"}),h();return}O(),b();try{const e=await g(l,i,m);if(e.hits.length===0){a.innerHTML="",c.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"topCenter"}),h();return}else E(e.hits),y.value="",H()}catch(e){console.error("Error fetching images:",e),c.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topCenter"})}finally{p()}}d.addEventListener("click",async()=>{try{d&&(i+=1);const t=await g(l,i,m),e=t.totalHits;E(t.hits),b(),m*i>=e&&(h(),C());const s=a.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:s*3,behavior:"smooth"})}catch(t){console.error("Error fetching more images:",t),c.error({title:"Error",message:`Error fetching more images: ${t}`})}finally{p()}});function b(){w.classList.remove("hidden")}function p(){w.classList.add("hidden")}function H(){d.style.display="block"}function h(){d.style.display="none"}function O(){const t=document.querySelector(".end-message");t&&t.remove()}window.addEventListener("scroll",()=>{document.body.scrollTop>30||document.documentElement.scrollTop>30?f.style.display="flex":f.style.display="none"});function $(){window.scrollTo({top:0,behavior:"smooth"})}f.addEventListener("click",$);
//# sourceMappingURL=commonHelpers.js.map
