import{a as E,S as w,i as a}from"./assets/vendor-da186403.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function n(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(r){if(r.ep)return;r.ep=!0;const o=n(r);fetch(r.href,o)}})();const $="42710952-cb07850fe6c5f6774b64d780f",v="https://pixabay.com/api/";async function m(t,e,n){try{return(await E.get(`${v}?key=${$}&q=${t}&image_type=photo&orientation=horizontal&safesearch=true&page=${e}&per_page=${n}`)).data.hits}catch(s){throw console.error("Error fetching images:",s),s}}const c=document.querySelector(".gallery"),p=new w(".gallery a",{captionsData:"alt",captionDelay:250});p.refresh();function y(t){c.innerHTML="",t.forEach(e=>{const n=`
      <li class="card">
        <a href="${e.largeImageURL}" class="link">
          <img src="${e.webformatURL}" alt="${e.tags}">
          <ul class="list-container">
          <li class="item-description"><h3>Likes</h3> <p>${e.likes}</p></li>
          <li class="item-description"><h3>Views</h3> <p>${e.views}</p></li>
          <li class="item-description"><h3>Comments</h3> <p>${e.comments}</p></li>
          <li class="item-description"><h3>Downloads</h3> <p>${e.downloads}</p></li>
        </ul>
        </a>
        
      </li>
    `;c.insertAdjacentHTML("beforeend",n)}),p.refresh()}function S(){const t=document.createElement("p");t.textContent="We're sorry, but you've reached the end of search results.",postList.appendChild(t)}const C=document.querySelector(".form"),h=document.querySelector(".search-input"),g=document.querySelector(".loader"),d=document.querySelector(".load-more-btn");f();let i="",L=1;const u=15;C.addEventListener("submit",P);async function P(t){if(t.preventDefault(),i=h.value.trim(),console.log(i),i===""){a.error({title:"Error",message:"Please enter a search term.",position:"topCenter"});return}b();try{const e=await m(i,L,u);e.length===0?(c.innerHTML="",a.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"topCenter"})):(y(e),h.value="",d.style.display="flex")}catch(e){console.error("Error fetching images:",e),a.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topCenter"})}finally{f()}}d.addEventListener("click",async()=>{try{b();const t=await m(i,L+=1,u);y(t),t.length<u&&(d.style.display="none",S())}catch(t){console.error("Error fetching more images:",t),a.error({title:"Error",message:`Error fetching more images: ${t}`})}finally{f(),q()}});function q(){c.getBoundingClientRect().height,window.scrollBy({top:-document.body.scrollHeight,behavior:"smooth"})}function b(){g.classList.remove("hidden")}function f(){g.classList.add("hidden")}
//# sourceMappingURL=commonHelpers.js.map
